[wip] Create user
SW705E19/frontend pull request #18
Opened 2019-11-06 09:03 UTC by MathiasLybech

2019-11-12 07:52 UTC, Tekrus requested changes
Burde der ikke tilføjes en route for at komme ind på siden?

Herudover: Registrer knappen sidder fixed til bunden når man kører i mobile view: 
![image](https://user-images.githubusercontent.com/21969475/68652376-a055d880-0529-11ea-9e65-e5d003f11430.png)

2019-11-12 07:52 UTC, Moesgaarda commented on src/components/CreateUser/SelectMultiple.jsx
> +  }));
Er der en grund til at kun den ene bør læses fra database?

2019-11-12 07:52 UTC, Moesgaarda commented on src/components/CreateUser/CreateUser.test.jsx
> +    it('should render 7 <TextField />s', () => {
Hvad med tests på hvis man sætter forkert info ind i hvert text field?

2019-11-12 07:52 UTC, Moesgaarda commented on src/components/CreateUser/SelectMultiple.jsx
> +  },
skal det være grå? Kan man på en måde få den til at få info om farven fra parent eller sådan noget, så det passer med det globale tema?

2019-11-12 08:32 UTC, MathiasLybech commented on src/components/CreateUser/SelectMultiple.jsx
> +  }));
Tænkte umiddelbart fordi at mulige interesseområder skal ligge i databasen, da det nemt kan ændre sig. Hvorimod sprog er ligesom alt andet tekst som ikke ændrer sig og kan skrives i i18n.js

2019-11-13 08:23 UTC, Tekrus requested changes

2019-11-13 08:23 UTC, Moesgaarda commented on src/components/CreateUser/SelectMultiple.jsx
> +import Button from '@material-ui/core/Button';
```suggestion
```

2019-11-25 09:37 UTC, Fatdet requested changes

2019-11-25 09:37 UTC, Fatdet commented on public/assets/i18n/translations/da.json
> +  "typefirstname": "Indtast dit efternavn",
fornavn ikke efternavn

2019-11-25 09:37 UTC, Fatdet commented on public/assets/i18n/translations/da.json
> +  "typepasswordagain": "Indtast password igen",
password error er her ikke

2019-11-25 09:43 UTC, Fatdet approved these changes

2019-11-25 09:58 UTC, Tekrus requested changes
Generelt tests???

2019-11-25 09:58 UTC, Moesgaarda commented on src/components/CreateUser/UserForm.jsx
> +	var { t, classes } = props;
const eller let

2019-11-25 09:58 UTC, Moesgaarda commented on src/helpers/validation-functions.jsx
> +	let day = parseInt(parts[2], 10);
kan de her ikke være const? Du ændrer dem vel aldrig?

2019-11-25 09:58 UTC, Moesgaarda commented on src/helpers/validation-functions.jsx
> +	let re = /(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{6,}/;
const

2019-11-25 09:58 UTC, Moesgaarda commented on src/components/CreateUser/CreateUser.jsx
> +      this.state.dateOfBirth.dateOfBirthValid
indention er lidt spøjs her, er den ikke?

2019-11-25 09:58 UTC, Moesgaarda commented on src/components/CreateUser/MultipleSelection.jsx
> +		<div>
skal det være div? Kan det ikke være <>?

2019-11-25 09:58 UTC, Moesgaarda commented on src/components/CreateUser/UserForm.jsx
> +		<Container component="main" maxWidth="sm">
skal den her være main? er den ydre i layout ikke det?

2019-11-25 09:58 UTC, Moesgaarda commented on src/components/CreateUser/UserForm.jsx
> +		marginTop: theme.spacing(3)
```suggestion
```

2019-11-25 09:58 UTC, Moesgaarda commented on src/components/CreateUser/UserForm.jsx
> +		marginTop: theme.spacing(10),
```suggestion
```

2019-11-25 09:58 UTC, Moesgaarda commented on src/helpers/validation-functions.jsx
> +	console.log(firstPassword);
Fjern

2019-11-25 09:58 UTC, Moesgaarda commented on src/helpers/validation-functions.jsx
> +	console.log(secondPassword);
Fjern

2019-11-25 12:07 UTC, Tekrus approved these changes

2019-11-25 12:08 UTC, merged