[WIP] Edit service
SW705E19/frontend pull request #34
Opened 2019-11-25 13:50 UTC by andpaacoke

2019-12-04 17:20 UTC, jenspetur94 requested changes

2019-12-04 17:20 UTC, jenspetur94 commented on src/containers/CreateService/CreateService.jsx
> +				toast.error(this.props.t('getcategoriesnotifyfail'), {
Hvis du bytter om på rækkefølgen af catch og then burde du ikke behøves at have et return i dem.

2019-12-05 10:46 UTC, Eduardsen commented on src/containers/EditService/EditService.jsx
> +
linjefarm

2019-12-05 10:46 UTC, Tekrus requested changes
1) Delete virker ikke

2019-12-05 10:46 UTC, Moesgaarda commented on src/containers/CreateService/CreateService.jsx
>  		}
skal den sende til login hvis man ikke kan hente tingene ud?

2019-12-05 10:46 UTC, Moesgaarda commented on src/containers/EditService/EditService.jsx
> +import { Dialog, DialogTitle, DialogActions} from '@material-ui/core';
Alle imports fra core kan hentes ud i en import

2019-12-05 10:46 UTC, Moesgaarda commented on src/containers/EditService/EditService.jsx
> +		this.setState({service: service});
Failer hvis man vælger 0 kategorier

2019-12-05 10:46 UTC, Moesgaarda commented on src/containers/EditService/EditService.jsx
> +			return <Redirect to={'/login/'}/>;
Burde nok være forsiden

2019-12-09 09:52 UTC, Tekrus requested changes

2019-12-09 09:52 UTC, Moesgaarda commented on public/assets/i18n/translations/en.json
> +  "choosecategories": "Choose atleast one category"
```suggestion
  "choosecategories": "Choose at least one category"
```

2019-12-09 09:54 UTC, Eduardsen commented on public/assets/i18n/translations/en.json
> +  "choosecategories": "Choose atleast one category"
yikes

2019-12-09 09:54 UTC, Eduardsen approved these changes

2019-12-09 10:10 UTC, jenspetur94 approved these changes

2019-12-09 10:15 UTC, Tekrus approved these changes

2019-12-09 10:16 UTC, merged