Edit user
SW705E19/frontend pull request #41
Opened 2019-12-05 13:23 UTC by MathiasLybech

2019-12-05 13:29 UTC, Moesgaarda commented on public/assets/i18n/translations/da.json
> +  "saveeditusernotifyfail": "The changes have not been saved"
```suggestion
  "saveeditusernotifyfail": "The changes have not been saved",
```

2019-12-05 13:30 UTC, Tekrus reviewed
komma

2019-12-09 10:03 UTC, Fatdet requested changes

2019-12-09 10:03 UTC, Fatdet commented on public/assets/i18n/translations/da.json
> +  "saveeditusernotifysuccess": "The changes was saved",
nice dansk

2019-12-09 10:03 UTC, Fatdet commented on public/assets/i18n/translations/da.json
> +  "saveeditusernotifyfail": "The changes have not been saved",
igen

2019-12-09 10:03 UTC, Fatdet commented on public/assets/i18n/translations/en.json
> +  "saveeditusernotifysuccess": "Ændringerne er nu gemt",
nice english

2019-12-09 10:03 UTC, Fatdet commented on public/assets/i18n/translations/en.json
> +  "saveeditusernotifyfail": "Ændringerne blev ikke gemt",
igen

2019-12-09 10:03 UTC, Fatdet commented on src/components/EditUser/EditUser.jsx
> +		});
mangler en catch eller noget til at håndtere fejl

2019-12-09 10:03 UTC, Fatdet commented on src/components/EditUser/EditUser.jsx
> +			userService.editUser(this.props.match.params.id, user);
igen en catch

2019-12-09 10:03 UTC, Fatdet commented on src/components/EditUser/EditUser.jsx
> +export default EditUser;
Du kommer nok til at skulle bruge en with translation her når du bruger din catch til fejl meddelser

2019-12-09 10:03 UTC, Fatdet commented on src/components/EditUser/EditUser.jsx
> +		return this.state.languageValues || this.state.subjectOfInterestValues ? (
Er det stadig nødvendigt? blev det ikke fixet i backend

2019-12-09 10:03 UTC, Fatdet commented on src/components/EditUser/EditUserForm.jsx
> +							{/* TODO: Her skal redirectes ens brugerside*/}
Skal det ordnes eller er det ordnet?

2019-12-09 10:03 UTC, Fatdet commented on src/hoc/Layout/Layout.jsx
> +			<Header />
Er det meningen det skal fjernes?

2019-12-09 11:18 UTC, MathiasLybech commented on src/components/EditUser/EditUser.jsx
> +		return this.state.languageValues || this.state.subjectOfInterestValues ? (
Ja, den skal stadigvæk være der.

2019-12-09 12:15 UTC, andpaacoke requested changes

2019-12-09 12:15 UTC, andpaacoke commented on src/hoc/Layout/Layout.jsx
> +						<Route path="/edituser/:id" component={EditUser} />
```suggestion
						<Route path="/user/edit/:id" component={EditUser} />
```

2019-12-09 12:29 UTC, Fatdet approved these changes

2019-12-09 12:59 UTC, andpaacoke approved these changes

2019-12-09 13:00 UTC, merged