Updated render user to show tutor info
SW705E19/frontend pull request #43
Opened 2019-12-09 11:50 UTC by Moesgaarda

2019-12-09 12:15 UTC, Eduardsen requested changes
Mangler der ikke nogle engelske oversættelser?

2019-12-09 12:24 UTC, Eduardsen commented on src/components/ShowUser/RenderUser/RenderUser.jsx
> +						{t('subjectofinterest')}: {props.user.subjectsOfInterest}
De ser lidt blown ud, der er ikke mellemrum eller noget formatering når de bliver skrevet

2019-12-09 12:24 UTC, Eduardsen commented on src/components/ShowUser/RenderUser/RenderUser.jsx
> +						{t('dateOfBirth')}: {props.user.dateOfBirth}
date of birth skrives som 2019-11-27T00:00:00.000Z, måske skal det formateres lidt

2019-12-09 12:24 UTC, Eduardsen commented on src/components/ShowUser/RenderUser/RenderUser.jsx
> +													{x.name} {x.id}
er det nødvendigt at vise id for et service her?

2019-12-09 12:24 UTC, MathiasLybech commented
![bemærkninger](https://user-images.githubusercontent.com/22811778/70435472-362c4700-1a87-11ea-8f5d-bc70e87673ad.png)

2019-12-09 12:45 UTC, Eduardsen approved these changes

2019-12-10 08:17 UTC, MathiasLybech approved these changes

2019-12-10 08:17 UTC, merged