Admin edit user
SW705E19/frontend pull request #48
Opened 2019-12-13 10:43 UTC by Fatdet

2019-12-13 12:15 UTC, MathiasLybech requested changes

2019-12-13 12:15 UTC, MathiasLybech commented on public/assets/i18n/translations/da.json
> +  "showAllServicesTitle": "Services",
Burde den ikke være i begge translations filer?

2019-12-13 12:15 UTC, MathiasLybech commented on public/assets/i18n/translations/da.json
>    "learnmore": "Læs mere",
oversættelserne til toastify skal være:
"saveeditusernotifysuccess": "The changes have not been saved",
 "saveeditusernotifyfail": "The changes were not saved",

2019-12-13 12:15 UTC, MathiasLybech commented on src/components/GiveTutorRole/GiveTutorGetUsers.jsx
> +			return {users,};
Hvad er formålet med at return users og hvorfor er der et komma?

2019-12-13 12:15 UTC, MathiasLybech commented on src/components/GiveTutorRole/GiveTutorGetUsers.jsx
> +		console.log(users[e.index].roles);
dræb console.log

2019-12-13 12:15 UTC, MathiasLybech commented on src/components/GiveTutorRole/GiveTutorRoleForm.jsx
> +			minWidth: 450,
Den her blower måske designet i mobil

2019-12-13 12:15 UTC, MathiasLybech commented on src/components/GiveTutorRole/GiveTutorRoleForm.jsx
> +				<Table className={classes.table} size="small" aria-label="a dense table">
Hvad gør aria-label="a dense table" ? 

Muligvis bare fjern

2019-12-13 12:15 UTC, Eduardsen commented on src/services/user/user.service.jsx
> +		body: jsonService};
```suggestion
		body: jsonService
		};
```

2019-12-14 09:55 UTC, Fatdet commented on src/components/GiveTutorRole/GiveTutorGetUsers.jsx
> +			return {users,};
Ellers opdatere den ikke staten

2019-12-14 11:41 UTC, Eduardsen approved these changes

2019-12-14 11:45 UTC, MathiasLybech approved these changes

2019-12-14 11:55 UTC, merged