Ratingidid
SW705E19/frontend pull request #50
Opened 2019-12-14 16:02 UTC by Fatdet

fixed avg, fixed null checks on userid, fixed giving only one rating

2019-12-15 15:50 UTC, Tekrus requested changes

2019-12-15 15:50 UTC, Moesgaarda commented on public/assets/i18n/translations/da.json
> +  "failgettingyourrating": "Kunne ikke hente din rating",
```suggestion
  "failgettingyourrating": "Kunne ikke hente din bedømmelse",
```

2019-12-15 15:50 UTC, Moesgaarda commented on public/assets/i18n/translations/en.json
> +  "failgettingyourrating": "Kunne ikke hente din rating",
```suggestion
  "failgettingyourrating": "Could not find your rating",
```

2019-12-15 15:50 UTC, Moesgaarda commented on src/components/ShowService/RenderService/RenderService.jsx
> +	//const [ratingValue, setRatingValue] = React.useState(0);
Udkommenteret kode?

2019-12-15 15:50 UTC, Moesgaarda commented on public/assets/i18n/translations/da.json
> +  "norating": "Ingen"
er "norating" en god key til det? Hvad med renderService.none ?

2019-12-15 15:50 UTC, Moesgaarda commented on public/assets/i18n/translations/da.json
> +  "norating": "Ingen gennemsnitlig rating"
```suggestion
  "norating": "Ingen gennemsnitlig bedømmelse"
```

2019-12-16 09:52 UTC, Tekrus approved these changes

2019-12-16 10:11 UTC, andpaacoke approved these changes

2019-12-16 10:14 UTC, merged